version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/app"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
    groups:
      docker-updates:
        patterns: ["*"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
    groups:
      github-actions-updates:
        patterns: ["*"]
  - package-ecosystem: "npm"
    directory: "/app"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
    groups:
      npm-updates:
        patterns: ["*"]
  - package-ecosystem: "terraform"
    directory: "/terraform"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
    groups:
      terraform-updates:
        patterns: ["*"]
  - package-ecosystem: "terraform"
    directory: "/terraform/environments/dev"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
    groups:
      terraform-updates:
        patterns: ["*"]
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/cloudwatch"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
    groups:
      terraform-updates:
        patterns: ["*"]
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/codebuild"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
    groups:
      terraform-updates:
        patterns: ["*"]
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/codepipeline"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
    groups:
      terraform-updates:
        patterns: ["*"]
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/ecr"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
    groups:
      terraform-updates:
        patterns: ["*"]
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/ecs"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
    groups:
      terraform-updates:
        patterns: ["*"]
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/iam"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
    groups:
      terraform-updates:
        patterns: ["*"]
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/networking"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
    groups:
      terraform-updates:
        patterns: ["*"]
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/security"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
    groups:
      terraform-updates:
        patterns: ["*"]
